binop_separator = "Front"
blank_lines_upper_bound = 2
doc_comment_code_block_width = 80
edition = "2021"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
imports_granularity = "Module"
match_arm_blocks = false
max_width = 80
newline_style = "Unix"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
reorder_impl_items = true
unstable_features = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
